#!/bin/bash

lang=$1
total=5

times=()
for i in $(seq 1 $total); do
    echo -en "\rRunning test for $lang: $i/$total"
    result="$(docker run --rm hellos-$lang 2>&1)"
    if [ $? -ne 0 ]; then
        echo -e "\rError running test for $lang:"
        echo "$result"
        exit 1
    fi
    time="$(echo "$result" | grep real | awk '{print $2}')"
    times+=("$(echo "$time" | awk -Fm '{print $1*60+$2}' | awk -F. '{print $1"."substr($2,1,3)}')")
done

# echo "$result"

echo -en "\rAverage for $lang: "
echo "${times[@]}" | awk -F' ' '{sum+=$1} END {print (sum/NR * 1000), "ms            "}'
